[project]
name = "gex-worker"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Jonatha-Varjao", email = "jonathavarjao@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "asyncmy>=0.2.11",
    "faststream[rabbit]>=0.6.7",
    "gex-common",
    "httpx>=0.28.1",
    "sqlalchemy[asyncio]>=2.0",
]

[project.scripts]
gex-worker = "gex_worker:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv.sources]
gex-common = { workspace = true }
