-- GEX Webhook Pipeline - Schema Creation
-- Database: gex
-- Character set: utf8mb4
-- All primary keys use CHAR(36) for UUIDv7 (generated by the application layer).
-- All timestamps use TIMESTAMP(6) for microsecond precision (lag calculation).

CREATE DATABASE IF NOT EXISTS gex
    CHARACTER SET utf8mb4;

USE gex;

-- ------------------------------------------------------------------
-- 1. raw_payloads: every webhook received, regardless of outcome.
--    Persists the raw body, decrypted body (when applicable), and
--    a processing_status string from the gex_common constants.
--    processing_status values:
--      'accepted' | 'decrypt_failed' | 'schema_failed'
--      'duplicate' | 'discarded_non_approved'
-- ------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS raw_payloads (
    id                CHAR(36)     NOT NULL,
    gateway           VARCHAR(32)  NOT NULL,
    received_at       TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    headers           JSON         NOT NULL,
    body_original     JSON         NOT NULL,
    body_decrypted    JSON         NULL,
    processing_status VARCHAR(32)  NOT NULL,
    error_detail      TEXT         NULL,
    correlation_id    CHAR(36)     NOT NULL,
    PRIMARY KEY (id),
    INDEX idx_raw_gateway_time (gateway, received_at),
    INDEX idx_raw_status (processing_status),
    INDEX idx_raw_correlation (correlation_id),
    INDEX idx_raw_received_at (received_at)
) ENGINE=InnoDB;

-- ------------------------------------------------------------------
-- 2. processed_events: lightweight idempotency guard.
--    Receiver-layer dedup before the worker creates the relational
--    records. UNIQUE (gateway, transaction_id, event) doubles as
--    the natural-key index for INSERT ON DUPLICATE KEY UPDATE.
-- ------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS processed_events (
    id             CHAR(36)     NOT NULL,
    gateway        VARCHAR(32)  NOT NULL,
    transaction_id VARCHAR(128) NOT NULL,
    event          VARCHAR(64)  NOT NULL,
    correlation_id CHAR(36)     NOT NULL,
    created_at     TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE INDEX uk_processed_events_natural (gateway, transaction_id, event),
    INDEX idx_processed_events_correlation (correlation_id)
) ENGINE=InnoDB;

-- ------------------------------------------------------------------
-- 3. leads: customer base. UNIQUE on normalized email.
--    Email is normalized (trim + lowercase) by gex_common.validation
--    before insert so casing differences resolve to the same row.
-- ------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS leads (
    id         CHAR(36)     NOT NULL,
    email      VARCHAR(255) NOT NULL,
    first_name VARCHAR(255) NOT NULL DEFAULT 'Customer',
    last_name  VARCHAR(255) NULL,
    phone      VARCHAR(20)  NULL,
    country    CHAR(2)      NOT NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)
                    ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE INDEX uk_leads_email (email)
) ENGINE=InnoDB;

-- ------------------------------------------------------------------
-- 4. orders: one row per (gateway, transaction_id). FK to leads.
--    Holds the full commercial detail of the sale.
-- ------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS orders (
    id               CHAR(36)      NOT NULL,
    lead_id          CHAR(36)      NOT NULL,
    gateway          VARCHAR(32)   NOT NULL,
    transaction_id   VARCHAR(128)  NOT NULL,
    transaction_time TIMESTAMP(6)  NOT NULL,
    event            VARCHAR(64)   NOT NULL,
    product_id       VARCHAR(128)  NOT NULL,
    product_name     VARCHAR(255)  NOT NULL,
    product_niche    VARCHAR(64)   NOT NULL,
    quantity         INT           NOT NULL,
    amount_usd       DECIMAL(10,2) NOT NULL,
    payment_method   VARCHAR(64)   NOT NULL,
    payment_status   VARCHAR(64)   NOT NULL,
    correlation_id   CHAR(36)      NOT NULL,
    created_at       TIMESTAMP(6)  NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE INDEX uk_orders_gateway_txn (gateway, transaction_id),
    INDEX idx_orders_lead (lead_id),
    INDEX idx_orders_product (product_id),
    INDEX idx_orders_event (event),
    INDEX idx_orders_correlation (correlation_id),
    INDEX idx_orders_gateway_created (gateway, created_at),
    CONSTRAINT fk_orders_leads FOREIGN KEY (lead_id) REFERENCES leads(id)
) ENGINE=InnoDB;

-- ------------------------------------------------------------------
-- 5. lead_events: per-event audit log. The UNIQUE (order_id, event)
--    IS the idempotency key for the worker's lead persistence path.
--    lag_seconds is a stored DECIMAL (sub-second precision); the
--    worker computes it from gateway_timestamp and db_timestamp.
-- ------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS lead_events (
    id                CHAR(36)        NOT NULL,
    order_id          CHAR(36)        NOT NULL,
    correlation_id    CHAR(36)        NOT NULL,
    event             VARCHAR(64)     NOT NULL,
    gateway_timestamp TIMESTAMP(6)    NOT NULL,
    db_timestamp      TIMESTAMP(6)    NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    lag_seconds       DECIMAL(10,3)   NULL,
    created_at        TIMESTAMP(6)    NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE INDEX uk_lead_events_order_event (order_id, event),
    INDEX idx_lead_events_correlation (correlation_id),
    INDEX idx_lead_events_event_time (event, gateway_timestamp),
    INDEX idx_lead_events_event (event),
    CONSTRAINT fk_lead_events_orders FOREIGN KEY (order_id) REFERENCES orders(id)
) ENGINE=InnoDB;

-- ------------------------------------------------------------------
-- 6. distribution_status: one row per (order, channel).
--    Holds the channel, status, attempts, and the lag from
--    DB persistence to channel delivery.
--    channel values: 'SMS' | 'EMAIL' | 'CALL_CENTER' | 'WHATSAPP'
--    status values:  'pending' | 'delivered' | 'failed'
-- ------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS distribution_status (
    id                        CHAR(36)      NOT NULL,
    order_id                  CHAR(36)      NOT NULL,
    correlation_id            CHAR(36)      NOT NULL
                                            DEFAULT '00000000-0000-0000-0000-000000000000',
    channel                   VARCHAR(32)   NOT NULL,
    status                    VARCHAR(32)   NOT NULL DEFAULT 'pending',
    attempts                  INT           NOT NULL DEFAULT 0,
    next_retry_at             TIMESTAMP(6)  NULL,
    delivered_at              TIMESTAMP(6)  NULL,
    lag_db_to_channel_seconds DECIMAL(10,3) NULL,
    error_detail              TEXT          NULL,
    created_at                TIMESTAMP(6)  NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at                TIMESTAMP(6)  NOT NULL DEFAULT CURRENT_TIMESTAMP(6)
                                  ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE INDEX uk_dist_order_channel (order_id, channel),
    INDEX idx_dist_channel_status_time (channel, status, created_at),
    INDEX idx_dist_delivered_at (channel, delivered_at),
    INDEX idx_dist_pending_since (status, created_at),
    INDEX idx_dist_order (order_id),
    INDEX idx_dist_correlation (correlation_id),
    CONSTRAINT fk_dist_orders FOREIGN KEY (order_id) REFERENCES orders(id)
) ENGINE=InnoDB;

-- ------------------------------------------------------------------
-- 7. lead_dead_letter: persistent record of DLQ entries.
--    origin: queue name (e.g. 'lead.dead.decrypt_failed',
--                          'dist.dead.sms', 'lead.dead.consumer_failed')
--    channel: NULL for receiver-side failures, channel name for
--             distributor-side failures.
-- ------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS lead_dead_letter (
    id             CHAR(36)     NOT NULL,
    origin         VARCHAR(128) NOT NULL,
    channel        VARCHAR(32)  NULL,
    payload        JSON         NOT NULL,
    error_reason   TEXT         NOT NULL,
    correlation_id CHAR(36)     NOT NULL,
    created_at     TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    INDEX idx_dlq_origin_time (origin, created_at),
    INDEX idx_dlq_correlation (correlation_id),
    INDEX idx_dlq_created_at (created_at)
) ENGINE=InnoDB;
