-- GEX Webhook Pipeline - Stored Procedures
-- ----------------------------------------------------------------------------
-- sp_insert_lead: Atomic lead persistence.
--
-- Called by the worker consumer after it pulls a message from
-- lead.received. Performs the three INSERTs in a single transaction:
--   1. leads     (upsert by email)
--   2. orders    (upsert by gateway+transaction_id)
--   3. lead_events + distribution_status (insert-if-new, by order_id+event)
--
-- All UUIDv7 ids are generated by the application layer (Python) and
-- passed in. This keeps UUID generation consistent (time-sortable) and
-- avoids relying on MySQL's UUID() (which is v1, not v7).
--
-- The returned `is_new` flag tells the caller whether lead_events was
-- actually created (True) or whether the event already existed (False).
-- On a duplicate event, distribution_status rows are NOT re-created;
-- the existing rows are preserved.
-- ----------------------------------------------------------------------------

DELIMITER //

DROP PROCEDURE IF EXISTS sp_insert_lead //

CREATE PROCEDURE sp_insert_lead(
    IN p_lead_id                CHAR(36),
    IN p_order_id               CHAR(36),
    IN p_event_id               CHAR(36),
    IN p_dist_sms_id            CHAR(36),
    IN p_dist_email_id          CHAR(36),
    IN p_dist_callcenter_id     CHAR(36),
    IN p_dist_whatsapp_id       CHAR(36),
    IN p_email                  VARCHAR(255),
    IN p_first_name             VARCHAR(255),
    IN p_last_name              VARCHAR(255),
    IN p_phone                  VARCHAR(20),
    IN p_country                CHAR(2),
    IN p_gateway                VARCHAR(32),
    IN p_transaction_id         VARCHAR(128),
    IN p_transaction_time       TIMESTAMP(6),
    IN p_event                  VARCHAR(64),
    IN p_product_id             VARCHAR(128),
    IN p_product_name           VARCHAR(255),
    IN p_product_niche          VARCHAR(64),
    IN p_quantity               INT,
    IN p_amount_usd             DECIMAL(10,2),
    IN p_payment_method         VARCHAR(64),
    IN p_payment_status         VARCHAR(64),
    IN p_correlation_id         CHAR(36),
    IN p_lag_seconds            DECIMAL(10,3)
)
BEGIN
    DECLARE v_existing_event_count INT DEFAULT 0;
    DECLARE v_is_new               TINYINT DEFAULT 0;

    DECLARE EXIT HANDLER FOR SQLEXCEPTION
    BEGIN
        ROLLBACK;
        RESIGNAL;
    END;

    START TRANSACTION;

    -- 1. Upsert lead by email. On conflict, refresh mutable fields.
    INSERT INTO leads (id, email, first_name, last_name, phone, country)
    VALUES (p_lead_id, p_email, p_first_name, p_last_name, p_phone, p_country) AS new
    ON DUPLICATE KEY UPDATE
        first_name = new.first_name,
        last_name  = new.last_name,
        phone      = new.phone,
        country    = new.country,
        updated_at = CURRENT_TIMESTAMP(6);

    -- Resolve the actual lead id (may differ from p_lead_id when the
    -- lead already existed under a different UUID).
    SELECT id INTO p_lead_id FROM leads WHERE email = p_email;

    -- 2. Upsert order by (gateway, transaction_id).
    INSERT INTO orders (
        id, lead_id, gateway, transaction_id, transaction_time, event,
        product_id, product_name, product_niche, quantity, amount_usd,
        payment_method, payment_status, correlation_id
    ) VALUES (
        p_order_id, p_lead_id, p_gateway, p_transaction_id,
        p_transaction_time, p_event, p_product_id, p_product_name,
        p_product_niche, p_quantity, p_amount_usd, p_payment_method,
        p_payment_status, p_correlation_id
    ) AS new
    ON DUPLICATE KEY UPDATE
        payment_status = new.payment_status,
        amount_usd     = new.amount_usd,
        product_id     = new.product_id,
        product_name   = new.product_name,
        product_niche  = new.product_niche,
        quantity       = new.quantity,
        payment_method = new.payment_method,
        correlation_id = new.correlation_id;

    -- Resolve the actual order id (may differ from p_order_id when the
    -- order already existed under a different UUID).
    SELECT id INTO p_order_id FROM orders WHERE gateway = p_gateway AND transaction_id = p_transaction_id;

    -- 3. Idempotency check: if (order_id, event) already exists, skip.
    SELECT COUNT(*) INTO v_existing_event_count
    FROM lead_events
    WHERE order_id = p_order_id AND event = p_event;

    IF v_existing_event_count = 0 THEN
        INSERT INTO lead_events (
            id, order_id, correlation_id, event,
            gateway_timestamp, db_timestamp, lag_seconds
        ) VALUES (
            p_event_id, p_order_id, p_correlation_id, p_event,
            p_transaction_time, CURRENT_TIMESTAMP(6), p_lag_seconds
        );

        INSERT IGNORE INTO distribution_status (id, order_id, channel, status)
        VALUES
            (p_dist_sms_id,        p_order_id, 'SMS',         'pending'),
            (p_dist_email_id,      p_order_id, 'EMAIL',       'pending'),
            (p_dist_callcenter_id, p_order_id, 'CALL_CENTER', 'pending'),
            (p_dist_whatsapp_id,   p_order_id, 'WHATSAPP',    'pending');

        SET v_is_new = 1;
    END IF;

    COMMIT;

    -- Return shape consumed by the worker.
    SELECT
        p_order_id  AS order_id,
        p_lead_id   AS lead_id,
        v_is_new    AS is_new;
END //

DELIMITER ;
